name: Build X-chat-GPT APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.build_type) || 'debug' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip libstdc++6 zlib1g-dev libffi-dev libssl-dev libltdl-dev libtinfo5
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
    - name: Cache buildozer build directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-build-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-build-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install buildozer==1.5.0 cython==0.29.33
        
    - name: Build APK with Buildozer
      run: |
        buildozer android $BUILD_TYPE -v
        
    - name: List build output
      run: |
        ls -la bin/ || true
        
    - name: Upload APK artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: X-chat-GPT-${{ env.BUILD_TYPE }}-${{ github.run_number }}
        path: bin/*.apk
        if-no-files-found: warn
        retention-days: 30
        
    - name: Create Release (if release build)
      if: env.BUILD_TYPE == 'release' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}